chromedriver_path: "./chromedriver"
alpha_path: "./alphas.txt"
# setting
region: "USA"  # region
univid: "TOP3000"  # universe
delay: "1"  # delay
decay: "4"  # decay
optrunc: "0.1"  # max stock weight
opneut: "subindustry"  # neutralization, 頭文字小文字
